'use client';

import { useState, useEffect } from 'react';

const CountdownTimer = () => {
  const calculateTimeLeft = () => {
    const difference = +new Date('2030-01-01T00:00:00') - +new Date();
    let timeLeft: { [key: string]: number } = {};

    if (difference > 0) {
      timeLeft = {
        days: Math.floor(difference / (1000 * 60 * 60 * 24)),
        hours: Math.floor((difference / (1000 * 60 * 60)) % 24),
        minutes: Math.floor((difference / 1000 / 60) % 60),
        seconds: Math.floor((difference / 1000) % 60),
      };
    }

    return timeLeft;
  };

  const [timeLeft, setTimeLeft] = useState<{ [key: string]: number }>({});

  useEffect(() => {
    // Set initial time on client to avoid hydration mismatch
    setTimeLeft(calculateTimeLeft());

    const timer = setTimeout(() => {
      setTimeLeft(calculateTimeLeft());
    }, 1000);

    return () => clearTimeout(timer);
  });

  const timerComponents: JSX.Element[] = [];

  Object.keys(timeLeft).forEach((interval) => {
    if (timeLeft[interval] === undefined) {
      return;
    }
    timerComponents.push(
      <div key={interval} className="text-center">
        <span className="text-lg font-bold">
          {String(timeLeft[interval]).padStart(2, '0')}
        </span>
        <span className="text-[0.4rem] uppercase tracking-wider">{interval}</span>
      </div>
    );
  });

  return (
    <div className="flex justify-center gap-3">
      {timerComponents.length ? timerComponents : <span>Time's up!</span>}
    </div>
  );
};


type FooterProps = {
    quote: string;
}

const Footer = ({ quote }: FooterProps) => {
  return (
    <footer className="w-full py-1 px-4 text-center text-foreground">
      <CountdownTimer />
      <p className="text-lg font-headline tracking-widest mt-1">VISION 2030</p>
      <p className="text-xs text-muted-foreground mt-0.5 h-3">
        {quote}
      </p>
       <p className="text-[0.6rem] text-muted-foreground mt-1">
        Quotes are generated by SASHA AI a product of MIR BIN ALI
      </p>
    </footer>
  );
};

export default Footer;
